# Makefile для тестов
CC = gcc
CFLAGS = -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -I.

TEST_SRCS = nginx_test_mocks_impl.c test_module_impl.c unit_tests.c
TEST_OBJS = $(TEST_SRCS:.c=.o)
TEST_BIN = test_module

.PHONY: all clean test

all: test

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

$(TEST_BIN): $(TEST_OBJS)
	$(CC) $(CFLAGS) -o $@ $(TEST_OBJS)

test: $(TEST_BIN)
	./$(TEST_BIN)

clean:
	rm -f $(TEST_OBJS) $(TEST_BIN)